version: "3.7"
############### Using Docker_SWARM ###############
services:
      ########## Services MariaDB ##########
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD= #mysql_root_password
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
      - MYSQL_PASSWORD=    #mysql_user_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - default
    deploy:
     placement:
      constraints:
       - "node.role==manager"

      ########## Services Redis ##########
  redis:
    image: redis:alpine
    networks:
      - default
     
      ########## Nextcloud_Apache ##########
  nextcloud-apache:
    image: nextcloud:apache
    volumes:
      - nextcloud:/var/www/html:z
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_PASSWORD= #mysql_user_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    deploy:  
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.local`)" #test domain
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
     
     placement:
      constraints:
       - "node.role==manager"
    depends_on:
      - db
      - redis
    networks:
      - default
      - proxynet

      ########## Cron ##########
  cron:
    image: nextcloud:apache
    volumes:
      - nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - default
    deploy:
     placement:
      constraints:
       - "node.role==manager"

volumes:
  db:
  nextcloud:

networks:
 proxynet:
  external: true

    
